### ISSUE TITLE
Exclaves are randomly taken or not taken into account when calculating border distance

### ISSUE THREAD

**Issue by omen-rigby** [the-abe-train/globle#103]
I can't see the logic app uses. Compare two examples below:

1. Mystery country: Azerbaijan. Guess: Turkey. Result: 0 km
2. Mystery country: Lithuania. Guess: Russia. Result: 110 km

Azerbaijan and Russia have exclaves that actually have border with Turkey/Lithuania respectively. Not sure what will happen if you swap guess country and mystery country in any of the examples.

FAQ mentions that overseas territories are ignored for UK & France, but the general rule is unclear.

**Comment by the-abe-train** [comment]
There isn't a hard rule for dealing with exclaves and territories, I manage them on a case-by-case basis. When I make these decisions, my intent is to make the game more playable by detaching the area of land that people normally think of as the country itself (e.g. Russia) from places that are technically part of that country (e.g. Kaliningrad) but would be confusing to someone trying to triangulate the position of the main country using the logic of the game.

One exception: In the case of Morocco, I made a Western Sahara a "territory" in the game, not because it is an exclave but because it is disputed, and the [framework](https://www.sporcle.com/blog/2013/01/what-is-a-country/) I use for determining "What is a country?" excludes it. This is the only example of that logic in the game.

All territories in the game, which are filled in with gray, are excluded from distance calculations.

I am going to do some research on the exclave of Azerbaijan to decide whether it should be considered a territory in the game.

**Comment by epixian** [comment]
> When I make these decisions, my intent is to make the game more playable by detaching the area of land that people normally think of as the country itself (e.g. Russia) from places that are technically part of that country (e.g. Kaliningrad)

I actually find those things quite interesting, and have gotten much enjoyment from discovering these little-known borders, and I would never have learned them otherwise.  Please keep them in the game!
