### ISSUE TITLE
Lithuania Borders Russia

### ISSUE THREAD

**Issue by SwingGuy1024** [the-abe-train/globle#105]
Today's mystery country was Lithuania. When I guessed Russia, it came up dark red, but not the deep dark red of a country that borders the mystery country. So Lithuania was one of the countries I ruled out.  But Lithuania does border Russia's western enclave of Kaliningrad. This small piece of land also borders Poland and the Baltic Sea. It's borders with Lithuania and Poland should be acknowledged by the game.

**Comment by the-abe-train** [comment]
Territories (areas that appear in gray when their parent country is guessed) are not included in any distance calculations. This includes Kaliningrad. I'm going to add info this to the first FAQ's answer in the next update.

**Comment by epixian** [comment]
I agree with @SwingGuy1024 and think Kaliningrad should be included in distance calculations.

There are at least two other instances where exclaves _are_ being included in distance calculations, with connections to other countries not otherwise accessible from the "main" country:
* Azerbaijan has a small little exclave that allows it to border Turkey
* Croatia's southern tip is an exclave that borders Macedonia

Adding Kaliningrad back in as part of Russia would at least make this consistent.
