### ISSUE TITLE
Pacific regions missing

### ISSUE THREAD

**Issue by BigPacificBrain** [the-abe-train/globle#135]
Hey, there’s HEAPS of countries in the pacific region that are missing that make this game almost impossible to play when it’s in that region. Some missing countries are:
Niue 
Tokelau
French Polynesia 
American Samoa
Tahiti
New Caledonia 

there’s more than this but these were my missing guesses in todays globle. 

Cheers for fixing fam

**Comment by alistaircarscadden** [comment]
The game [cites](https://globle-game.com/info) this article as it's method of designating whether somewhere is a country or not:

[What is a country? And how many are there?](https://www.sporcle.com/blog/2013/01/what-is-a-country/)

For example, French Polynesia does not meet the criteria because "[is an overseas collectivity of France and its sole overseas country](https://en.wikipedia.org/wiki/French_Polynesia)" where overseas country "[[is] merely a designation and not a legal status](https://en.wikipedia.org/wiki/Overseas_country_of_France)".
