### ISSUE TITLE
Puzzle resetting

### ISSUE THREAD

**Issue by ywjm** [the-abe-train/globle#27]
The Globle FAQ states that "The mystery country changes and your guesses reset at midnight in your time zone". I live in GMT+8 and the puzzle reset at 12am in my time zone (Malta was the correct answer). I had managed to guess Malta in 7 tries previously. However, I opened the game again at around 10.45am but the puzzle had changed and all my previous guesses still stayed there but were all light-coloured. The solution had changed to Thailand. Is this a bug? Even if the puzzle did not reset at 12am in my timezone, surely my guesses would have reset?

**Comment by the-abe-train** [comment]
I'm sorry about that. I pushed a change that changed the order of countries, and I tried to time it so that it would affect as few people as possible, but alas your time-zone was in the splash-zone. I could have handled this change better, and it's my fault your game was messed up today. I'll make sure it won't happen again, and I hope you keep playing.
