### ISSUE TITLE
Add a 'give up' mechanism

### ISSUE THREAD

**Issue by tjiang11** [the-abe-train/globle#30]
For the geographically challenged like myself, I think it makes sense to add a 'give up' button. Otherwise, in order to complete the game, the user needs to inconveniently whip out an external map and look up the answer. If the user wants to still figure out the answer on their own with a map, it could be sort of two steps where the first step just makes sure to handle streak/averages/sharing of results appropriately, and the second step, if the user so desires, reveals the actual answer. I don't want to have to keep saying "I had to use a map for this btw" while sharing my results every time I have to look up the answer with a map. It also completely skews my real "streak" and "average".

As for the streak, I think it makes more sense for the "streak" to be how many times in a row you were able to guess the country without help.

Just my opinion! Thanks for the fun game!

**Comment by the-abe-train** [comment]
I understand the reasoning behind this, but this is one feature that I am not going to add, at least not in the near future. I worry that making giving up easier will encourage more people to give up. I want people to go to Google Maps, or Google Earth, or even open up an atlas when they can't find the answer because I believe that is the best way to learn geography. 

All of that said, I do appreciate your feedback and interest in improving the game!
