### ISSUE TITLE
Denmark is confusing

### ISSUE THREAD

**Issue by JeremyLeland** [the-abe-train/globle#9]
When I entered "Denmark" as a guess, I got this:
![denmark_or_greenland](https://user-images.githubusercontent.com/50390633/152666335-e41aecee-d9e9-4e82-8ae1-f8dd2e8c8900.png)

Initially, I thought this was a bug, since it appears to be showing Greenland. On a lark, I read the Wikipedia page for Greenland, where I learned that a portion of Greenland is part of the Kingdom of Denmark (which I didn't realize was a thing until today).

So I guess this isn't necessarily wrong, but it is confusing. Also, it makes me question the meaning of the color value -- does the red mean the answer is close to Greenland? Or close to Denmark?

Anyway, just wanted to get this on your radar, since it's kind of a weird case.

**Comment by SqlSusan** [comment]
It is a little confusing. Technically Greenland is owned by Denmark, but still called Greenland. Much in the same way British territories are.

**Comment by the-abe-train** [comment]
Currently, when Denmark is guessed, both Greenland and Denmark light up. This is because, according to the source that I am using to define "what is a country",
> While Greenland is largely autonomous in many ways, it is not itself a member of the U.N. and still officially part of of the kingdom of Denmark. Its area is represented as Denmark.

That said, I definitely see why it is confusing, especially given that the globe rotates to Greenland when Denmark is guessed. This is a quirk of the rotating function centring the globe on the largest landmass of each country. Denmark is the only country in which the largest landmass is not really the country itself.

I am considering removing Greenland from the game altogether. This would mean that if Denmark is guessed, only Denmark lights up, and if Greenland is guessed, then nothing happens. If you think that would be the best solution, please +1 (👍) this post. If you think it should stay the same, then 👎, and if you have a preferred solution, please add it to this thread.

Thank you all for helping me improve the game!

**Comment by JeremyLeland** [comment]
Is there a way to spin the globe to focus on the area with largest population density rather than largest landmass? Looks like Greenland is the least densely populated region in the world.

**Comment by the-abe-train** [comment]
@JeremyLeland that is a possibility I didn't think of! Removing Greenland might still be preferable, but this is also an option.

**Comment by IanDLacy** [comment]
This threw me off for a moment also. Is it possible to treat Greenland separate from Denmark? I feel like most people and maps view it as a separate entity anyway.

**Comment by the-abe-train** [comment]
I just pushed an update that marks territories (e.g. Greenland and French Guiana) as a neutral colour when their sovereign country is guessed. Try it out and let me know if anything else needs to be cleared up!
